image:
  jakzal/phpqa

before_script:
    - cd api
    - composer install

cache:
  paths:
    - vendor/

stages:
  - phpstan
  - php-cs-fixer
  - phpunit

phpstan:
  stage: phpstan
  script:
    - phpstan analyse --level=1 src
  allow_failure: true

php-cs-fixer:
  image: jakzal/phpqa
  stage: php-cs-fixer
  script:
      - ci/php-cs-fixer.sh
  artifacts:
      paths:
          - var/patch.diff
      expire_in: 24 hrs
      when: on_failure
  allow_failure: true

phpunit:
  stage: phpunit
  script:
    - php bin/phpunit
  allow_failure: true