api_platform:
    title: LamAPI
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # ajout des formats de données supportés
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good defaults value for REST APIs
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 51
        pagination_items_per_page: 51
         # Good cache defaults
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
    # http_cache:
    #     invalidation:
    #         enabled: true
    #         varnish_urls: ['%env(VARNISH_URL)%']
    #     public: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
    # Utilisation du metadata system
