<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220530091547 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE address (id UUID NOT NULL, city_id UUID DEFAULT NULL, name VARCHAR(50) NOT NULL, street VARCHAR(255) NOT NULL, postal_code VARCHAR(10) NOT NULL, hr_mail_address VARCHAR(255) NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D4E6F818BAC62AF ON address (city_id)');
        $this->addSql('COMMENT ON COLUMN address.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN address.city_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE badge (id UUID NOT NULL, label VARCHAR(255) NOT NULL, image_uri VARCHAR(255) NOT NULL, description TEXT NOT NULL, badge_path VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN badge.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE city (id UUID NOT NULL, department_id UUID DEFAULT NULL, zip_code VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D5B0234AE80F5DF ON city (department_id)');
        $this->addSql('COMMENT ON COLUMN city.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN city.department_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_entity (id UUID NOT NULL, company_group_id UUID DEFAULT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, offices_number INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33B7201DE6C3CC2A ON company_entity (company_group_id)');
        $this->addSql('COMMENT ON COLUMN company_entity.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_entity.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_entity_offices_addresses (company_entity_id UUID NOT NULL, address_id UUID NOT NULL, PRIMARY KEY(company_entity_id, address_id))');
        $this->addSql('CREATE INDEX IDX_430B3959B23EF7AD ON company_entity_offices_addresses (company_entity_id)');
        $this->addSql('CREATE INDEX IDX_430B3959F5B7AF75 ON company_entity_offices_addresses (address_id)');
        $this->addSql('COMMENT ON COLUMN company_entity_offices_addresses.company_entity_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_entity_offices_addresses.address_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group (id UUID NOT NULL, logo_id UUID DEFAULT NULL, header_media_id UUID DEFAULT NULL, main_media_id UUID DEFAULT NULL, social_id UUID DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, referral_code VARCHAR(255) DEFAULT NULL, career_website BOOLEAN NOT NULL, open_to_recruitment BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(100) NOT NULL, creation_year INT DEFAULT NULL, global_hr_mail_address VARCHAR(255) DEFAULT NULL, turnover INT DEFAULT NULL, us_text TEXT DEFAULT NULL, values TEXT DEFAULT NULL, customers_desc VARCHAR(255) DEFAULT NULL, customers_number INT DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2A31E6A0F98F144A ON company_group (logo_id)');
        $this->addSql('CREATE INDEX IDX_2A31E6A05B42DC0F ON company_group (header_media_id)');
        $this->addSql('CREATE INDEX IDX_2A31E6A033BDCC00 ON company_group (main_media_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A31E6A0FFEB5B27 ON company_group (social_id)');
        $this->addSql('COMMENT ON COLUMN company_group.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group.logo_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group.header_media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group.main_media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group.social_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_medias (company_group_id UUID NOT NULL, media_id UUID NOT NULL, PRIMARY KEY(company_group_id, media_id))');
        $this->addSql('CREATE INDEX IDX_3F99BD9FE6C3CC2A ON company_group_medias (company_group_id)');
        $this->addSql('CREATE INDEX IDX_3F99BD9FEA9FDD75 ON company_group_medias (media_id)');
        $this->addSql('COMMENT ON COLUMN company_group_medias.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_medias.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_pools (company_group_id UUID NOT NULL, pool_id UUID NOT NULL, PRIMARY KEY(company_group_id, pool_id))');
        $this->addSql('CREATE INDEX IDX_5687EB48E6C3CC2A ON company_group_pools (company_group_id)');
        $this->addSql('CREATE INDEX IDX_5687EB487B3406DF ON company_group_pools (pool_id)');
        $this->addSql('COMMENT ON COLUMN company_group_pools.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_pools.pool_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_partners (company_group_id UUID NOT NULL, organisation_id UUID NOT NULL, PRIMARY KEY(company_group_id, organisation_id))');
        $this->addSql('CREATE INDEX IDX_C81332B8E6C3CC2A ON company_group_partners (company_group_id)');
        $this->addSql('CREATE INDEX IDX_C81332B89E6B1585 ON company_group_partners (organisation_id)');
        $this->addSql('COMMENT ON COLUMN company_group_partners.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_partners.organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_has_badge (id UUID NOT NULL, company_group_id UUID DEFAULT NULL, badge_id UUID DEFAULT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8A3B3E3FE6C3CC2A ON company_group_has_badge (company_group_id)');
        $this->addSql('CREATE INDEX IDX_8A3B3E3FF7A2C2FC ON company_group_has_badge (badge_id)');
        $this->addSql('COMMENT ON COLUMN company_group_has_badge.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_has_badge.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_has_badge.badge_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_has_job_type (id UUID NOT NULL, company_group_id UUID DEFAULT NULL, job_type_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_450876DAE6C3CC2A ON company_group_has_job_type (company_group_id)');
        $this->addSql('CREATE INDEX IDX_450876DA5FA33B08 ON company_group_has_job_type (job_type_id)');
        $this->addSql('COMMENT ON COLUMN company_group_has_job_type.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_has_job_type.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_has_job_type.job_type_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_has_tool (id UUID NOT NULL, company_group_id UUID DEFAULT NULL, tool_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5A578652E6C3CC2A ON company_group_has_tool (company_group_id)');
        $this->addSql('CREATE INDEX IDX_5A5786528F7B22CC ON company_group_has_tool (tool_id)');
        $this->addSql('COMMENT ON COLUMN company_group_has_tool.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_has_tool.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_has_tool.tool_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_subscription (id UUID NOT NULL, company_group_id UUID DEFAULT NULL, subscription_id UUID DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FCBAC955E6C3CC2A ON company_group_subscription (company_group_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FCBAC9559A1887DC ON company_group_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN company_group_subscription.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_subscription.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_team (id UUID NOT NULL, company_group_id UUID DEFAULT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_503414F9E6C3CC2A ON company_group_team (company_group_id)');
        $this->addSql('COMMENT ON COLUMN company_group_team.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_team.company_group_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_team_medias (company_group_team_id UUID NOT NULL, media_id UUID NOT NULL, PRIMARY KEY(company_group_team_id, media_id))');
        $this->addSql('CREATE INDEX IDX_1DEC6661D34EAEDF ON company_group_team_medias (company_group_team_id)');
        $this->addSql('CREATE INDEX IDX_1DEC6661EA9FDD75 ON company_group_team_medias (media_id)');
        $this->addSql('COMMENT ON COLUMN company_group_team_medias.company_group_team_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_team_medias.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE company_group_team_media (id UUID NOT NULL, company_group_team_id UUID DEFAULT NULL, media_id UUID DEFAULT NULL, description TEXT DEFAULT NULL, destination VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_541C7545D34EAEDF ON company_group_team_media (company_group_team_id)');
        $this->addSql('CREATE INDEX IDX_541C7545EA9FDD75 ON company_group_team_media (media_id)');
        $this->addSql('COMMENT ON COLUMN company_group_team_media.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_team_media.company_group_team_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN company_group_team_media.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE department (id UUID NOT NULL, region_id UUID DEFAULT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CD1DE18A98260155 ON department (region_id)');
        $this->addSql('COMMENT ON COLUMN department.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN department.region_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE job_type (id UUID NOT NULL, label VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN job_type.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE media (id UUID NOT NULL, content_url VARCHAR(255) DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN media.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE media_image (id UUID NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN media_image.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE media_video (id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN media_video.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE offer (id UUID NOT NULL, company_entity_id UUID DEFAULT NULL, address_id UUID DEFAULT NULL, provided BOOLEAN NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, job_title INT NOT NULL, contract_type VARCHAR(255) NOT NULL, fully_telework BOOLEAN NOT NULL, weekly_hours DOUBLE PRECISION NOT NULL, level_of_study INT NOT NULL, start_asap BOOLEAN NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, salary_min DOUBLE PRECISION NOT NULL, salary_max DOUBLE PRECISION NOT NULL, experience INT NOT NULL, missions TEXT NOT NULL, needs TEXT NOT NULL, works_with_us TEXT NOT NULL, prospects_with_us TEXT NOT NULL, recruitment_process TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_29D6873EB23EF7AD ON offer (company_entity_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29D6873EF5B7AF75 ON offer (address_id)');
        $this->addSql('COMMENT ON COLUMN offer.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN offer.company_entity_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN offer.address_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE offer_tools (offer_id UUID NOT NULL, tool_id UUID NOT NULL, PRIMARY KEY(offer_id, tool_id))');
        $this->addSql('CREATE INDEX IDX_69D7A39E53C674EE ON offer_tools (offer_id)');
        $this->addSql('CREATE INDEX IDX_69D7A39E8F7B22CC ON offer_tools (tool_id)');
        $this->addSql('COMMENT ON COLUMN offer_tools.offer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN offer_tools.tool_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE offer_external_platform (id UUID NOT NULL, offer_id UUID DEFAULT NULL, platform VARCHAR(255) NOT NULL, external_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D3AFF05F53C674EE ON offer_external_platform (offer_id)');
        $this->addSql('COMMENT ON COLUMN offer_external_platform.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN offer_external_platform.offer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE organisation (id UUID NOT NULL, logo_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, website VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E6E132B4F98F144A ON organisation (logo_id)');
        $this->addSql('COMMENT ON COLUMN organisation.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN organisation.logo_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE pool (id UUID NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN pool.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE region (id UUID NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN region.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE social (id UUID NOT NULL, linkedin VARCHAR(255) NOT NULL, twitter VARCHAR(255) NOT NULL, facebook VARCHAR(255) NOT NULL, instagram VARCHAR(255) NOT NULL, youtube VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN social.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription (id UUID NOT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN subscription.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE tool (id UUID NOT NULL, logo_id UUID DEFAULT NULL, header_media_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_20F33ED1F98F144A ON tool (logo_id)');
        $this->addSql('CREATE INDEX IDX_20F33ED15B42DC0F ON tool (header_media_id)');
        $this->addSql('COMMENT ON COLUMN tool.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tool.logo_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tool.header_media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F818BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_entity ADD CONSTRAINT FK_33B7201DE6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_entity_offices_addresses ADD CONSTRAINT FK_430B3959B23EF7AD FOREIGN KEY (company_entity_id) REFERENCES company_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_entity_offices_addresses ADD CONSTRAINT FK_430B3959F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group ADD CONSTRAINT FK_2A31E6A0F98F144A FOREIGN KEY (logo_id) REFERENCES media_image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group ADD CONSTRAINT FK_2A31E6A05B42DC0F FOREIGN KEY (header_media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group ADD CONSTRAINT FK_2A31E6A033BDCC00 FOREIGN KEY (main_media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group ADD CONSTRAINT FK_2A31E6A0FFEB5B27 FOREIGN KEY (social_id) REFERENCES social (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_medias ADD CONSTRAINT FK_3F99BD9FE6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_medias ADD CONSTRAINT FK_3F99BD9FEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_pools ADD CONSTRAINT FK_5687EB48E6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_pools ADD CONSTRAINT FK_5687EB487B3406DF FOREIGN KEY (pool_id) REFERENCES pool (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_partners ADD CONSTRAINT FK_C81332B8E6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_partners ADD CONSTRAINT FK_C81332B89E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_has_badge ADD CONSTRAINT FK_8A3B3E3FE6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_has_badge ADD CONSTRAINT FK_8A3B3E3FF7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_has_job_type ADD CONSTRAINT FK_450876DAE6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_has_job_type ADD CONSTRAINT FK_450876DA5FA33B08 FOREIGN KEY (job_type_id) REFERENCES job_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_has_tool ADD CONSTRAINT FK_5A578652E6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_has_tool ADD CONSTRAINT FK_5A5786528F7B22CC FOREIGN KEY (tool_id) REFERENCES tool (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_subscription ADD CONSTRAINT FK_FCBAC955E6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_subscription ADD CONSTRAINT FK_FCBAC9559A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_team ADD CONSTRAINT FK_503414F9E6C3CC2A FOREIGN KEY (company_group_id) REFERENCES company_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_team_medias ADD CONSTRAINT FK_1DEC6661D34EAEDF FOREIGN KEY (company_group_team_id) REFERENCES company_group_team (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_team_medias ADD CONSTRAINT FK_1DEC6661EA9FDD75 FOREIGN KEY (media_id) REFERENCES company_group_team_media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_team_media ADD CONSTRAINT FK_541C7545D34EAEDF FOREIGN KEY (company_group_team_id) REFERENCES company_group_team (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE company_group_team_media ADD CONSTRAINT FK_541C7545EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A98260155 FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_image ADD CONSTRAINT FK_DA24C0EEBF396750 FOREIGN KEY (id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_video ADD CONSTRAINT FK_63DE1E9DBF396750 FOREIGN KEY (id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer ADD CONSTRAINT FK_29D6873EB23EF7AD FOREIGN KEY (company_entity_id) REFERENCES company_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer ADD CONSTRAINT FK_29D6873EF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_tools ADD CONSTRAINT FK_69D7A39E53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_tools ADD CONSTRAINT FK_69D7A39E8F7B22CC FOREIGN KEY (tool_id) REFERENCES tool (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_external_platform ADD CONSTRAINT FK_D3AFF05F53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organisation ADD CONSTRAINT FK_E6E132B4F98F144A FOREIGN KEY (logo_id) REFERENCES media_image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pool ADD CONSTRAINT FK_AF91A986BF396750 FOREIGN KEY (id) REFERENCES organisation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tool ADD CONSTRAINT FK_20F33ED1F98F144A FOREIGN KEY (logo_id) REFERENCES media_image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tool ADD CONSTRAINT FK_20F33ED15B42DC0F FOREIGN KEY (header_media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE company_entity_offices_addresses DROP CONSTRAINT FK_430B3959F5B7AF75');
        $this->addSql('ALTER TABLE offer DROP CONSTRAINT FK_29D6873EF5B7AF75');
        $this->addSql('ALTER TABLE company_group_has_badge DROP CONSTRAINT FK_8A3B3E3FF7A2C2FC');
        $this->addSql('ALTER TABLE address DROP CONSTRAINT FK_D4E6F818BAC62AF');
        $this->addSql('ALTER TABLE company_entity_offices_addresses DROP CONSTRAINT FK_430B3959B23EF7AD');
        $this->addSql('ALTER TABLE offer DROP CONSTRAINT FK_29D6873EB23EF7AD');
        $this->addSql('ALTER TABLE company_entity DROP CONSTRAINT FK_33B7201DE6C3CC2A');
        $this->addSql('ALTER TABLE company_group_medias DROP CONSTRAINT FK_3F99BD9FE6C3CC2A');
        $this->addSql('ALTER TABLE company_group_pools DROP CONSTRAINT FK_5687EB48E6C3CC2A');
        $this->addSql('ALTER TABLE company_group_partners DROP CONSTRAINT FK_C81332B8E6C3CC2A');
        $this->addSql('ALTER TABLE company_group_has_badge DROP CONSTRAINT FK_8A3B3E3FE6C3CC2A');
        $this->addSql('ALTER TABLE company_group_has_job_type DROP CONSTRAINT FK_450876DAE6C3CC2A');
        $this->addSql('ALTER TABLE company_group_has_tool DROP CONSTRAINT FK_5A578652E6C3CC2A');
        $this->addSql('ALTER TABLE company_group_subscription DROP CONSTRAINT FK_FCBAC955E6C3CC2A');
        $this->addSql('ALTER TABLE company_group_team DROP CONSTRAINT FK_503414F9E6C3CC2A');
        $this->addSql('ALTER TABLE company_group_team_medias DROP CONSTRAINT FK_1DEC6661D34EAEDF');
        $this->addSql('ALTER TABLE company_group_team_media DROP CONSTRAINT FK_541C7545D34EAEDF');
        $this->addSql('ALTER TABLE company_group_team_medias DROP CONSTRAINT FK_1DEC6661EA9FDD75');
        $this->addSql('ALTER TABLE city DROP CONSTRAINT FK_2D5B0234AE80F5DF');
        $this->addSql('ALTER TABLE company_group_has_job_type DROP CONSTRAINT FK_450876DA5FA33B08');
        $this->addSql('ALTER TABLE company_group DROP CONSTRAINT FK_2A31E6A05B42DC0F');
        $this->addSql('ALTER TABLE company_group DROP CONSTRAINT FK_2A31E6A033BDCC00');
        $this->addSql('ALTER TABLE company_group_medias DROP CONSTRAINT FK_3F99BD9FEA9FDD75');
        $this->addSql('ALTER TABLE company_group_team_media DROP CONSTRAINT FK_541C7545EA9FDD75');
        $this->addSql('ALTER TABLE media_image DROP CONSTRAINT FK_DA24C0EEBF396750');
        $this->addSql('ALTER TABLE media_video DROP CONSTRAINT FK_63DE1E9DBF396750');
        $this->addSql('ALTER TABLE tool DROP CONSTRAINT FK_20F33ED15B42DC0F');
        $this->addSql('ALTER TABLE company_group DROP CONSTRAINT FK_2A31E6A0F98F144A');
        $this->addSql('ALTER TABLE organisation DROP CONSTRAINT FK_E6E132B4F98F144A');
        $this->addSql('ALTER TABLE tool DROP CONSTRAINT FK_20F33ED1F98F144A');
        $this->addSql('ALTER TABLE offer_tools DROP CONSTRAINT FK_69D7A39E53C674EE');
        $this->addSql('ALTER TABLE offer_external_platform DROP CONSTRAINT FK_D3AFF05F53C674EE');
        $this->addSql('ALTER TABLE company_group_partners DROP CONSTRAINT FK_C81332B89E6B1585');
        $this->addSql('ALTER TABLE pool DROP CONSTRAINT FK_AF91A986BF396750');
        $this->addSql('ALTER TABLE company_group_pools DROP CONSTRAINT FK_5687EB487B3406DF');
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A98260155');
        $this->addSql('ALTER TABLE company_group DROP CONSTRAINT FK_2A31E6A0FFEB5B27');
        $this->addSql('ALTER TABLE company_group_subscription DROP CONSTRAINT FK_FCBAC9559A1887DC');
        $this->addSql('ALTER TABLE company_group_has_tool DROP CONSTRAINT FK_5A5786528F7B22CC');
        $this->addSql('ALTER TABLE offer_tools DROP CONSTRAINT FK_69D7A39E8F7B22CC');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE company_entity');
        $this->addSql('DROP TABLE company_entity_offices_addresses');
        $this->addSql('DROP TABLE company_group');
        $this->addSql('DROP TABLE company_group_medias');
        $this->addSql('DROP TABLE company_group_pools');
        $this->addSql('DROP TABLE company_group_partners');
        $this->addSql('DROP TABLE company_group_has_badge');
        $this->addSql('DROP TABLE company_group_has_job_type');
        $this->addSql('DROP TABLE company_group_has_tool');
        $this->addSql('DROP TABLE company_group_subscription');
        $this->addSql('DROP TABLE company_group_team');
        $this->addSql('DROP TABLE company_group_team_medias');
        $this->addSql('DROP TABLE company_group_team_media');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE job_type');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE media_image');
        $this->addSql('DROP TABLE media_video');
        $this->addSql('DROP TABLE offer');
        $this->addSql('DROP TABLE offer_tools');
        $this->addSql('DROP TABLE offer_external_platform');
        $this->addSql('DROP TABLE organisation');
        $this->addSql('DROP TABLE pool');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE social');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE tool');
    }
}
